// Generated by scripts/embed-schema.sh from Schemas/jev-systemone-request.schema.json. Do not edit.

public enum JevRequestSchema {
    /// Jev's JSON Schema (draft 2020-12) for systemOne requests.
    public static let json = #"""
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "state": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "object",
              "propertyNames": {
                "type": "string"
              },
              "additionalProperties": {
                "$ref": "#/$defs/__schema0"
              }
            },
            {
              "type": "array",
              "items": {
                "$ref": "#/$defs/__schema0"
              }
            },
            {
              "type": "null"
            }
          ]
        },
        "questions": {
          "type": "object",
          "propertyNames": {
            "type": "string",
            "minLength": 1
          },
          "additionalProperties": {
            "oneOf": [
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "noul"
                  },
                  "instructions": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "object",
                        "propertyNames": {
                          "type": "string"
                        },
                        "additionalProperties": {
                          "$ref": "#/$defs/__schema0"
                        }
                      },
                      {
                        "type": "array",
                        "items": {
                          "$ref": "#/$defs/__schema0"
                        }
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "criteria": {
                    "anyOf": [
                      {
                        "type": "object",
                        "properties": {
                          "true": {
                            "anyOf": [
                              {
                                "type": "string"
                              },
                              {
                                "type": "object",
                                "propertyNames": {
                                  "type": "string"
                                },
                                "additionalProperties": {
                                  "$ref": "#/$defs/__schema0"
                                }
                              },
                              {
                                "type": "array",
                                "items": {
                                  "$ref": "#/$defs/__schema0"
                                }
                              },
                              {
                                "type": "null"
                              }
                            ]
                          },
                          "false": {
                            "anyOf": [
                              {
                                "type": "string"
                              },
                              {
                                "type": "object",
                                "propertyNames": {
                                  "type": "string"
                                },
                                "additionalProperties": {
                                  "$ref": "#/$defs/__schema0"
                                }
                              },
                              {
                                "type": "array",
                                "items": {
                                  "$ref": "#/$defs/__schema0"
                                }
                              },
                              {
                                "type": "null"
                              }
                            ]
                          }
                        },
                        "additionalProperties": false
                      },
                      {
                        "type": "null"
                      }
                    ]
                  }
                },
                "required": [
                  "type",
                  "instructions"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "choice"
                  },
                  "instructions": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "object",
                        "propertyNames": {
                          "type": "string"
                        },
                        "additionalProperties": {
                          "$ref": "#/$defs/__schema0"
                        }
                      },
                      {
                        "type": "array",
                        "items": {
                          "$ref": "#/$defs/__schema0"
                        }
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "criteria": {
                    "type": "object",
                    "propertyNames": {
                      "type": "string"
                    },
                    "additionalProperties": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "object",
                          "propertyNames": {
                            "type": "string"
                          },
                          "additionalProperties": {
                            "$ref": "#/$defs/__schema0"
                          }
                        },
                        {
                          "type": "array",
                          "items": {
                            "$ref": "#/$defs/__schema0"
                          }
                        },
                        {
                          "type": "null"
                        }
                      ]
                    }
                  }
                },
                "required": [
                  "type",
                  "instructions",
                  "criteria"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "score"
                  },
                  "instructions": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "object",
                        "propertyNames": {
                          "type": "string"
                        },
                        "additionalProperties": {
                          "$ref": "#/$defs/__schema0"
                        }
                      },
                      {
                        "type": "array",
                        "items": {
                          "$ref": "#/$defs/__schema0"
                        }
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "criteria": {
                    "minItems": 2,
                    "type": "array",
                    "items": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "object",
                          "propertyNames": {
                            "type": "string"
                          },
                          "additionalProperties": {
                            "$ref": "#/$defs/__schema0"
                          }
                        },
                        {
                          "type": "array",
                          "items": {
                            "$ref": "#/$defs/__schema0"
                          }
                        },
                        {
                          "type": "null"
                        }
                      ]
                    }
                  }
                },
                "required": [
                  "type",
                  "instructions",
                  "criteria"
                ],
                "additionalProperties": false
              }
            ]
          }
        }
      },
      "required": [
        "state",
        "questions"
      ],
      "additionalProperties": false,
      "$defs": {
        "__schema0": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "number"
            },
            {
              "type": "boolean"
            },
            {
              "type": "null"
            },
            {
              "type": "array",
              "items": {
                "$ref": "#/$defs/__schema0"
              }
            },
            {
              "type": "object",
              "propertyNames": {
                "type": "string"
              },
              "additionalProperties": {
                "$ref": "#/$defs/__schema0"
              }
            }
          ]
        }
      }
    }
    """#

    /// The parsed, checked schema. Loading can only fail if the embedded text is broken,
    /// which the test suite rules out.
    public static let schema: JSONSchema = {
        do { return try JSONSchema(json: json) } catch { fatalError("embedded Jev schema is invalid: \(error)") }
    }()
}
