// Generated by scripts/embed-schema.sh from Schemas/jev-systemone-response.schema.json. Do not edit.

public enum JevResponseSchema {
    /// Jev's JSON Schema (draft 2020-12) for systemOne responses.
    public static let json = #"""
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "model": {
          "type": "string",
          "minLength": 1
        },
        "answers": {
          "type": "object",
          "propertyNames": {
            "type": "string",
            "minLength": 1
          },
          "additionalProperties": {
            "oneOf": [
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "noul"
                  },
                  "noul": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                  }
                },
                "required": [
                  "type",
                  "noul"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "choice"
                  },
                  "choice": {
                    "type": "string"
                  },
                  "probabilities": {
                    "type": "object",
                    "propertyNames": {
                      "type": "string"
                    },
                    "additionalProperties": {
                      "type": "number",
                      "minimum": 0,
                      "maximum": 1
                    }
                  },
                  "confidence": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                  }
                },
                "required": [
                  "type",
                  "choice",
                  "probabilities",
                  "confidence"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "score"
                  },
                  "score": {
                    "type": "number"
                  },
                  "legend": {
                    "type": "object",
                    "propertyNames": {
                      "type": "string"
                    },
                    "additionalProperties": {
                      "type": "string"
                    }
                  },
                  "probabilities": {
                    "type": "object",
                    "propertyNames": {
                      "type": "string"
                    },
                    "additionalProperties": {
                      "type": "number",
                      "minimum": 0,
                      "maximum": 1
                    }
                  },
                  "confidence": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                  }
                },
                "required": [
                  "type",
                  "score",
                  "legend",
                  "probabilities",
                  "confidence"
                ],
                "additionalProperties": false
              }
            ]
          }
        },
        "usage": {
          "type": "object",
          "properties": {
            "input_tokens": {
              "type": "integer",
              "minimum": 0,
              "maximum": 9007199254740991
            },
            "output_tokens": {
              "type": "integer",
              "minimum": 0,
              "maximum": 9007199254740991
            }
          },
          "required": [
            "input_tokens",
            "output_tokens"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "model",
        "answers",
        "usage"
      ],
      "additionalProperties": false
    }
    """#

    /// The parsed, checked schema. Loading can only fail if the embedded text is broken,
    /// which the test suite rules out.
    public static let schema: JSONSchema = {
        do { return try JSONSchema(json: json) } catch { fatalError("embedded Jev schema is invalid: \(error)") }
    }()
}
