#!/bin/sh
# Regenerates the embedded copies of Jev's schemas from Schemas/:
#   jev-systemone-request.schema.json  -> Sources/JevHosts/Schema/JevRequestSchema.swift
#   jev-systemone-response.schema.json -> Sources/JevHosts/Schema/JevResponseSchema.swift
# Together they are Jev's contract, whichever host serves it. JevHostsTests fails if a copy drifts.
set -eu
cd "$(dirname "$0")/.."

# embed <type name> <schema file> <doc line>
embed() {
  out="Sources/JevHosts/Schema/$1.swift"
  {
    echo "// Generated by scripts/embed-schema.sh from Schemas/$2. Do not edit."
    echo
    echo "public enum $1 {"
    echo "    /// $3"
    echo '    public static let json = #"""'
    sed 's/^/    /' "Schemas/$2"
    echo '    """#'
    echo
    echo '    /// The parsed, checked schema. Loading can only fail if the embedded text is broken,'
    echo '    /// which the test suite rules out.'
    echo '    public static let schema: JSONSchema = {'
    echo '        do { return try JSONSchema(json: json) } catch { fatalError("embedded Jev schema is invalid: \(error)") }'
    echo '    }()'
    echo '}'
  } > "$out"
  echo "wrote $out"
}

embed JevRequestSchema jev-systemone-request.schema.json "Jev's JSON Schema (draft 2020-12) for systemOne requests."
embed JevResponseSchema jev-systemone-response.schema.json "Jev's JSON Schema (draft 2020-12) for systemOne responses."
